export const registrationFieldItems = [
  {
    type: "text",
    id: "firstname",
    name: "firstname",
    label: "First Name",
    placeholder: "First name",
  },
  {
    type: "text",
    id: "lastname",
    name: "lastname",
    label: "Last Name",
    placeholder: "Last name",
  },
  {
    type: "countrySelector",
    id: "country",
    name: "country",
    label: "Country",
    placeholder: "Select Country",
  },
  {
    type: "email",
    id: "email",
    name: "email",
    label: "Email",
    placeholder: "Email",
  },
  {
    type: "password",
    id: "password",
    name: "password",
    label: "Password",
    placeholder: "Password",
  },
  {
    type: "password",
    id: "confirmpassword",
    name: "confirmpassword",
    label: "Confirm Password",
    placeholder: "Confirm Password",
  },
  {
    type: "checkbox",
    id: "policies",
    name: "policies",
    placeholder: "Accept Terms and Conditions",
  },
]
